//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weighingControlSystem.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_storemachineData
    {
        public long pkid { get; set; }
        public string truckRFIDIN { get; set; }
        public Nullable<long> truckMppigRFID { get; set; }
        public string truckRFIDOUT { get; set; }
        public string operatorRFID { get; set; }
        public string material { get; set; }
        public Nullable<decimal> grossWeight { get; set; }
        public Nullable<decimal> fairWeight { get; set; }
        public Nullable<decimal> netWeight { get; set; }
        public Nullable<long> shiftTime { get; set; }
        public string status { get; set; }
        public string ScaleId { get; set; }
        public Nullable<long> machinePkid { get; set; }
        public Nullable<long> serverId { get; set; }
        public long cid { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.DateTime> dateTimeMachine { get; set; }
        public Nullable<decimal> outGrossWeight { get; set; }
        public Nullable<decimal> outTairWeight { get; set; }
        public Nullable<decimal> outNetWeight { get; set; }
        public Nullable<System.DateTime> outTime { get; set; }
        public Nullable<long> outPkid { get; set; }
        public Nullable<long> outShift { get; set; }
        public string outLocation { get; set; }
    }
}
