//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weighingControlSystem.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RemoteConnection
    {
        public long pkid { get; set; }
        public string serverName { get; set; }
        public string dataBaseName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string comments { get; set; }
    }
}
