//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weighingControlSystem.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_weighingcontroller_demo
    {
        public long pkid { get; set; }
        public string serialNo { get; set; }
        public string RFID1 { get; set; }
        public string RFID { get; set; }
        public string shift { get; set; }
        public string TruckNumber { get; set; }
        public string createdDate { get; set; }
        public string createdTime { get; set; }
        public string oprator { get; set; }
        public string contactor { get; set; }
        public string Wheal1 { get; set; }
        public string wheal2 { get; set; }
        public string wheal3 { get; set; }
        public string wheal4 { get; set; }
        public string totalWeight { get; set; }
        public string GrossWeight { get; set; }
        public string netWeight { get; set; }
        public string truckCapacity { get; set; }
        public string fill_factor { get; set; }
        public string material { get; set; }
        public string scaleId { get; set; }
        public Nullable<long> cid { get; set; }
        public Nullable<long> mid { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
    }
}
