//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weighingControlSystem.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class weighingcontrolSystemEntities : DbContext
    {
        public weighingcontrolSystemEntities()
            : base("name=weighingcontrolSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_contractor> tbl_contractor { get; set; }
        public DbSet<tbl_operatorDetails> tbl_operatorDetails { get; set; }
        public DbSet<tbl_operatorMapiingWithContactor> tbl_operatorMapiingWithContactor { get; set; }
        public DbSet<tbl_operatorMapping> tbl_operatorMapping { get; set; }
        public DbSet<tbl_operatorshift> tbl_operatorshift { get; set; }
        public DbSet<tbl_RemoteConnection> tbl_RemoteConnection { get; set; }
        public DbSet<tbl_rfidDetails> tbl_rfidDetails { get; set; }
        public DbSet<tbl_TruckDetails> tbl_TruckDetails { get; set; }
        public DbSet<tbl_truckMapping> tbl_truckMapping { get; set; }
        public DbSet<tbl_weighingcontroller_demo> tbl_weighingcontroller_demo { get; set; }
        public DbSet<tbl_accessConnection> tbl_accessConnection { get; set; }
        public DbSet<tbl_storemachineData> tbl_storemachineData { get; set; }
    }
}
